#     $ bin/tkellem examples/config.yml
#
# to connect: connect to localhost port 10001, ssl enabled, "real name" set to
#
#     <connection_name> <client_name>
#
# e.g.:
#
#     freenode laptop
--- 
listen: 0.0.0.0
port: 10001
ssl: true
connections: 
  freenode:
    host: irc.freenode.org
    port: 6667
    ssl: false
    nick: tkellem_r0ck
    rooms: 
    - name: "#tkellem_test"
    clients: 
    - name: laptop
    - name: iphone
